Update all recipe references to xen packages
OXT-1694

Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

diff --git a/recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/resize-agent b/recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/resize-agent
--- a/recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/resize-agent
+++ b/recipes-openxt/xenclient-uivm-xsessionconfig/xenclient-uivm-xsessionconfig/resize-agent
@@ -5,7 +5,7 @@ if [ -f /usr/lib/openxt/ui-functions ];  then
 fi
 
 if ! command -v "xenstore-watch" >/dev/null; then
-    echo "XenStore utilities could not be found. Is xen-xenstore installed?" >&2
+    echo "XenStore utilities could not be found. Is xen-tools-xenstore installed?" >&2
     exit 1
 fi
 
