seal-system: Only measure root dev if sealing pcr15
When pcr15 isn't in the PCR selection, we can skip hashing the root
block device since the value will not be used.

OXT-1594

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system b/recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
--- a/recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
+++ b/recipes-openxt/openxt-measuredlaunch/openxt-measuredlaunch/seal-system
@@ -46,6 +46,18 @@ Usage: seal-system [-h] [-s|-u|-f] [-ctpgbr path] -[48 object[,objects]]"
 EOF
 }
 
+pcr_in_selection() {
+    pcr="$1"
+
+    for p in $pcr_selection ; do
+        if [ $p -eq $pcr ] ; then
+            return 0
+        fi
+    done
+
+    return 1
+}
+
 read_pcr_selection() {
     # strip out -r/-p to leave just the digits
     sed -e 's/-[rp]//g' $config_pcrs
@@ -236,21 +248,26 @@ forward)
         pcr_forward[8]=":${pcr8}"
     fi
 
-    [ -r ${root_dev} ] || err "cannot read root_dev ${root_dev}"
-    # During early init, rootfs is hashed and is given to
-    # tpm_extend which for tpm1.2 hashes the rootfs hash again and
-    # hands that value to the TPM to be extended into PCR 15
+    if pcr_in_selection 15 ; then
+        [ -r ${root_dev} ] || err "cannot read root_dev ${root_dev}"
+        # During early init, rootfs is hashed and is given to
+        # tpm_extend which for tpm1.2 hashes the rootfs hash again and
+        # hands that value to the TPM to be extended into PCR 15
 
-    # Use dd here to perform direct I/O. On some machines in some cases, stale data in
-    # the storage layer, or perhaps the disk cache, causes sha256sum {root_dev} to compute
-    # an incorrect hash, leading to a bad PCR15 value. Direct I/O always computes an accurate hash
-    # so we can correct predict PCR15 during forward seal.
-    root_hash=$(dd status=none if=${root_dev} iflag=direct bs=8M | ${hashalg}sum|cut -f1 -d' ')
-    [ "${tpm2}" -ne 0 ] && root_hash=$(echo -n ${root_hash}|${hashalg}sum|cut -f1 -d' ')
-    pcr15=$(hash_extend 0 ${root_hash} ${hashalg}) ||
-        err "failed to hash root device"
+        # Use dd here to perform direct I/O. On some machines in some cases,
+        # stale data in the storage layer, or perhaps the disk cache, causes
+        # sha256sum {root_dev} to compute an incorrect hash, leading to a bad
+        # PCR15 value. Direct I/O always computes an accurate hash so we can
+        # correct predict PCR15 during forward seal.
+        root_hash=$(dd status=none if=${root_dev} iflag=direct bs=8M | \
+                        ${hashalg}sum|cut -f1 -d' ')
+        [ "${tpm2}" -ne 0 ] && root_hash=$(echo -n ${root_hash} | \
+                                               ${hashalg}sum|cut -f1 -d' ')
+        pcr15=$(hash_extend 0 ${root_hash} ${hashalg}) ||
+                err "failed to hash root device"
 
-    pcr_forward[15]=":${pcr15}"
+        pcr_forward[15]=":${pcr15}"
+    fi
 
     # Calculate DRTM PCRs if set (ie. PCR17 is not all f)
     if ! contains_only "${pcr17}" "f"; then
