tpm-functions: Add tpm_check_owner_password
Add a test to see if we know the TPM owner password.

OXT-1130

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions b/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
--- a/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
+++ b/recipes-openxt/xenclient/xenclient-tpm-scripts/tpm-functions
@@ -191,6 +191,32 @@ tpm_is_owner_wks() {
     fi
     return $ret
 }
+# Function to determine if we have the TPM owner password
+# returns 0 if owner password is ${passwd}'s contents
+#         1 if owner password is not in ${passwd}
+#         2 if indeterminant
+tpm_check_owner_password() {
+    local passwd="$1"
+    local ret=0
+    local msg=""
+
+    is_tpm_2_0
+    local tpm2=$?
+    if [ "${tpm2}" -eq 0 ];
+    then
+        # Fail tpm2 owner check until we find a solution.
+        return 1
+    fi
+
+    msg=$(cat "${passwd}" | tpm_setenable --stdin -s 2>&1)
+    if [ $? -ne 0 ]; then
+        case "$msg" in
+            *Authentication\ failed) ret=1 ;;
+            *) ret=2 ;;
+        esac
+    fi
+    return $ret
+}
 # Function to determine whether or not the TPM SRK pasword is the well known
 #   20 bytes of 0's.
 # returns 0 if TPM SRK passwd is WKS
