verify-repo-metadata: Support more hashes
Use the hash length to determine which algorithm to use.

Signed-off-by: Jason Andryuk <jandryuk@gmail.com>

diff --git a/recipes-openxt/xenclient-repo-certs/xenclient-repo-certs/verify-repo-metadata b/recipes-openxt/xenclient-repo-certs/xenclient-repo-certs/verify-repo-metadata
--- a/recipes-openxt/xenclient-repo-certs/xenclient-repo-certs/verify-repo-metadata
+++ b/recipes-openxt/xenclient-repo-certs/xenclient-repo-certs/verify-repo-metadata
@@ -54,6 +54,24 @@ Exit status:
 EOF
 }
 
+get_hasher()
+{
+    case "${#1}" in
+    64)
+        echo "sha256sum"
+        ;;
+    96)
+        echo "sha384sum"
+        ;;
+    128)
+        echo "sha512sum"
+        ;;
+    *)
+        die "invalid checksum length"
+        ;;
+    esac
+}
+
 verify_xc_packages()
 {
     local PACKAGES_CHECKSUM=$(sed -n 's/^packages://p' "${REPOSITORY_FILE}") ||
@@ -62,7 +80,8 @@ verify_xc_packages()
     [ -n "${PACKAGES_CHECKSUM}" ] ||
         die "XC-PACKAGES checksum MISSING"
 
-    local FILE_CHECKSUM=$(sha256sum "${PACKAGES_FILE}" | cut -f1 -d' ') ||
+    local hasher="$( get_hasher "${PACKAGES_CHECKSUM}" )"
+    local FILE_CHECKSUM=$( "$hasher" "${PACKAGES_FILE}" | cut -f1 -d' ') ||
         die "error calculating checksum of '${PACKAGES_FILE}'"
 
     [ -n "${FILE_CHECKSUM}" ] ||
